#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_GOOGLE_include_directive : enable

/*
    second pass of exclusive scan
    add partial scan result
*/

layout (local_size_x = 1024) in;

//layout(push_constant) uniform Consts
//{
//  int n;
//}consts;

layout(std430, binding = 0) buffer Input
{
  uint value[];
}i;

layout(std430, binding = 1) buffer Output
{
  uint value[];
}o;

shared uint sum;

void main()
{
  //if (gl_WorkGroupID.x > 0 && gl_GlobalInvocationID.x < consts.n)
  if (gl_WorkGroupID.x > 0)
  {
    sum = 0;
//    if(gl_WorkGroupID.x > 0)
    if(gl_LocalInvocationID.x == 0)
        sum = i.value[gl_WorkGroupID.x - 1];

    memoryBarrierShared();
    barrier();


    o.value[gl_GlobalInvocationID.x] += sum;
  }
}