/*
 * Abura Soba, 2025
 * 
 * Full Ray Tracing
 *
 * linearInterpolation.comp
 *
 * Compute shader
 */

#version 460

//#extension GL_KHR_vulkan_glsl : enable

layout(local_size_x = 32, local_size_y = 32) in;



layout(binding = 0, set = 0, rgba8) uniform image2D image;

//TODO: edge handling
void main()
{
	uvec2 gridId = gl_GlobalInvocationID.xy * 2;
	gridId.x += 1;
	
	vec4 leftColor = imageLoad(image, ivec2(gridId.x - 1, gridId.y));
	vec4 rightColor = imageLoad(image, ivec2(gridId.x + 1, gridId.y));

	vec4 finalColor = (leftColor + rightColor) / 2;

	vec4 red = vec4(1.0f, 0.0f, 0.0f, 0.0f);
    imageStore(image, ivec2(gridId), finalColor);
}