/*
 * Sogang Univ, Graphics Lab, 2024
 * 
 * Abura Soba, 2025
 * 
 * Full Ray Tracing
 *
 * Ray generation shader
 */

#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_scalar_block_layout : require

#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_ray_flags_primitive_culling : require

#include "../base/3dgs.glsl"
#include "../base/utils.glsl"
#include "../base/define.glsl"

/***** 3DGS *****/
layout(location = 0) rayPayloadEXT RayPayload rayPayload;

layout(binding = 0, set = 0) uniform accelerationStructureEXT topLevelAS;
layout(binding = 1, set = 0, rgba8) uniform image2D image;
layout(binding = 2, set = 0) uniform uniformBuffer
{
	mat4 viewInverse;
	mat4 projInverse;
} uboDynamic;
layout(binding = 3, set = 0) uniform uniformBufferStatic
{
	Aabb aabb;
	float minTransmittance;
	float hitMinGaussianResponse;
	uint sphEvalDegree;
} uboStatic;

layout(std140, binding = 4, set = 0) buffer ParticleDensities {
	ParticleDensity d[];
} particleDensities;
layout(std430, binding = 5, set = 0) buffer ParticleSphCoefficients {
	float c[];
} particleSphCoefficients;	// [features_albedo(vec3), features_specular(float)]. uboStatic.particleRadiance

#if ENABLE_HIT_COUNTS || SIMILARITY_VAR
layout(std430, binding = 7, set = 0) buffer RayHitCounts {
	uint cnts[];
} rayHitCounts;
#endif

#if UNDERSAMPLING
	#if STATISTICS
layout(std430, binding = 8, set = 0) buffer RTMask{
	uint rtMask[];
};
layout(std430, binding = 15, set = 0) buffer FinalTransmittance{
	float finalTransmittance[];
};
	#endif
	#if SIMILARITY_VAR
layout(std430, binding = 9, set = 0) buffer ParticleIDs{
	uint id[];
};

layout(std430, binding = 10, set = 0) buffer Alpha{
	float alphaBuffer[];
};
layout(std430, binding = 11, set = 0) buffer Weight{
	float weightBuffer[];
};
layout(std430, binding = 12, set = 0) buffer SimilarityVar{
	float similarityVar[];
};
layout(std430, binding = 13, set = 0) buffer Depth{
	float depthBuffer[];
};
layout(std430, binding = 14, set = 0) buffer SimilVarValidCnt{
	uint validCnt[];
};
layout(std430, binding = 16, set = 0) buffer AccumDepth{
	float accumDepth[];
};
	#endif

layout(push_constant, std430) uniform pushConstant{
	uint width;
	uint height;
	uint additionalRT;
	float colorThreshold;
	float hitThreshold;
	float weightThreshold;
	float depthThreshold;
};
#endif

#if DEBUG_TOTAL_ISECTCNT
layout(std430, binding = 17, set = 0) buffer IsectCnt{
	uint isectCnt[];
};
#endif

#include "../base/gaussianfunctions.glsl"
#if UNDERSAMPLING
#include "../base/underSampling.glsl"
#endif

#if CHECK_BVH
vec3 hsv2rgb(vec3 c) {
    vec4 K = vec4(1.0, 2.0/3.0, 1.0/3.0, 3.0);
    vec3 p = abs(fract(c.xxx + K.xyz) * 6.0 - K.www);
    return c.z * mix(K.xxx, clamp(p - K.xxx, 0.0, 1.0), c.y);
}
#endif

/*** 3dgrt style ***/
void initializeRayPayload(){
	for(int i = 0; i < MAX_HIT_PER_TRACE; i++){
		rayPayload.hits[i].particleId = INVALID_PARTICLE_ID;
		rayPayload.hits[i].dist = INFINITE_DISTANCE;
	}
}

void trace(vec3 rayOri, vec3 rayDir, const float tmin, const float tmax){
	initializeRayPayload();
	traceRayEXT(topLevelAS, gl_RayFlagsSkipClosestHitShaderEXT | gl_RayFlagsCullBackFacingTrianglesEXT | gl_RayFlagsSkipAABBEXT, 0xff, 0, 0, 0, rayOri, tmin, rayDir, tmax, 0);
}

void main()
{
	// set ray origin, direction
#if UNDERSAMPLING
	vec2 pixelCenter;
	vec2 inUV;
	uvec2 targetPixel;
	uvec2 nearPixel1;
	uvec2 nearPixel2;
	//TODO: handle edge condition
	if(additionalRT == 0){
		targetPixel = gl_LaunchIDEXT.xy * 2;
		pixelCenter = vec2(targetPixel) + vec2(0.5);	// pixel position
		inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy * 2);	// pixel position in WdC
	}
	else{
		if(additionalRT == 1){
			targetPixel = gl_LaunchIDEXT.xy * 2 + ivec2(1,0);
			nearPixel1 = uvec2(targetPixel.x - 1, targetPixel.y);
			nearPixel2 = uvec2(targetPixel.x + 1, targetPixel.y);

			pixelCenter = vec2(targetPixel) + vec2(0.5);
			inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy * 2);	// pixel position in WdC
		}
		else{
			targetPixel = gl_LaunchIDEXT.xy;
			targetPixel.y = targetPixel.y * 2 + 1;
			nearPixel1 = uvec2(targetPixel.x, targetPixel.y - 1);
			nearPixel2 = uvec2(targetPixel.x, targetPixel.y + 1);
			pixelCenter = vec2(targetPixel) + vec2(0.5);	// pixel position
			inUV = pixelCenter/vec2(gl_LaunchSizeEXT.x, gl_LaunchSizeEXT.y * 2);	// pixel position in WdC
		}
		vec4 finalColor;
		bool similar = similarityCheck(nearPixel1, nearPixel2, targetPixel, finalColor);
		if(similar){
			imageStore(image, ivec2(targetPixel), finalColor);
			return;
		}
	}
	#if SIMILARITY_VAR
	uint similarityVarOffset = (targetPixel.y * width + targetPixel.x) * MAX_SIMILARITY_VAR;
	#endif
#else
	const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);	// pixel position
	const vec2 inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy);	// pixel position in WdC
#endif
	vec2 d = inUV * 2.0 - 1.0;	// pixel position in NDC
	vec4 rayOrigin = uboDynamic.viewInverse[3];
	vec4 target = uboDynamic.projInverse * vec4(d.x, d.y, 1.0f, 1.0f) ;	// (pixel position in EC) / Wc
	vec4 rayDirection = normalize(uboDynamic.viewInverse * vec4(target.xyz, 0.0f));

	/*** 3dgrt style ***/
	vec3 rayRadiance = vec3(0.0f, 0.0f, 0.0f);
	float rayTransmittance = 1.0f;
	float rayHitDistance = 0.0f;

	uint hitCount = 0;

#ifdef ENABLE_NORMALS
	vec3 rayNormal = vec3(0.0f);
#endif
#if ENABLE_HIT_COUNTS || SIMILARITY_VAR
	uint hitCnts = 0;
#endif
#if SIMILARITY_VAR
	float alpha;
	float weight;
	uint similVarIdx = 0;
	float depthSum = 0.0f;
#endif

	vec2 minMaxT = intersectAABB(uboStatic.aabb, rayOrigin.xyz, rayDirection.xyz);
	const float epsT = EPS_T;

	float rayLastHitDistance = max(0.0f, minMaxT.x - epsT);

	const uint iterations = ITERATIONS;
	uint iter = 0;
#if DEBUG_TOTAL_ISECTCNT
	rayPayload.isectCnt = 0;
#endif

#if CHECK_BVH
	trace(rayOrigin.xyz, rayDirection.xyz, rayLastHitDistance + epsT, minMaxT.y + epsT);
	if(rayPayload.hits[0].particleId != INVALID_PARTICLE_ID){
		uint particleId = rayPayload.hits[0].particleId;
		float hue = 0.55 + (float(particleId % 1000) / 1000.0) * 0.1;
		//float hue = float(particleId % 360) / 360.0;
		rayRadiance = hsv2rgb(vec3(hue, 0.6, 0.9));
	}
#else
	while((rayLastHitDistance <= minMaxT.y) && (rayTransmittance > uboStatic.minTransmittance)){
		iter++;

		// Gather k hits
		trace(rayOrigin.xyz, rayDirection.xyz, rayLastHitDistance + epsT, minMaxT.y + epsT);
		if(rayPayload.hits[0].particleId == INVALID_PARTICLE_ID){
			break;
		}

		// Process k hits
        for(int i = 0; i < MAX_HIT_PER_TRACE; i++){
			const RayHit rayHit = rayPayload.hits[nonuniformEXT(i)];

			if((rayHit.particleId != INVALID_PARTICLE_ID) && (rayTransmittance > uboStatic.minTransmittance)){
				const bool acceptedHit = processHit(
					rayOrigin.xyz,
					rayDirection.xyz,
					rayHit.particleId,
					uboStatic.hitMinGaussianResponse,
					ALPHA_MIN_THRESHOLD,
					uboStatic.sphEvalDegree,
					rayTransmittance,
					rayRadiance,
					rayHitDistance
#if SIMILARITY_VAR
					,alpha,
					weight
#endif
				);

#if UNDERSAMPLING && SIMILARITY_VAR
				if(acceptedHit){
					//if(similVarIdx < MAX_SIMILARITY_VAR){
					if(similVarIdx < MAX_SIMILARITY_VAR && weight >= weightThreshold){
						id[similarityVarOffset + similVarIdx] = rayHit.particleId;
						//alphaBuffer[similarityVarOffset + similVarIdx] = alpha;
						weightBuffer[similarityVarOffset + similVarIdx] = weight;
						depthSum += rayHitDistance;
						similVarIdx += 1;
					}
				}

				
#endif

				rayLastHitDistance = max(rayLastHitDistance, rayHit.dist);

#if ENABLE_HIT_COUNTS || SIMILARITY_VAR
				if(acceptedHit){
					hitCnts += 1;
				}
#endif
			}
		}
		#if MOBILE
		if(iter >= iterations) break;
		#endif
	}
#endif
	

#if UNDERSAMPLING
	imageStore(image, ivec2(targetPixel), vec4(rayRadiance, 1.0f));
	#if STATISTICS
	rtMask[targetPixel.y * width + targetPixel.x] = 1;
	finalTransmittance[targetPixel.y * width + targetPixel.x] = 1 - rayTransmittance;
	#endif
	#if ENABLE_HIT_COUNTS
	rayHitCounts.cnts[targetPixel.y * width + targetPixel.x] = hitCnts;
	#endif
	#if SIMILARITY_VAR
	validCnt[targetPixel.y * width + targetPixel.x] = similVarIdx;
	accumDepth[targetPixel.y * width + targetPixel.x] = 0.3;
	#endif
#else
    imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(rayRadiance, 1.0f));
	#if ENABLE_HIT_COUNTS
	rayHitCounts.cnts[gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x] = hitCnts;
	#endif
#endif

#if DEBUG_TOTAL_ISECTCNT
	isectCnt[gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x] = rayPayload.isectCnt;
#endif
}
