/*
 * Abura Soba, 2025
 * 
 * Full Ray Tracing
 *
 * linearInterpolation.comp
 *
 * Compute shader
 */

#version 460

#include "../base/underSampling.glsl"
//#extension GL_KHR_vulkan_glsl : enable

layout(local_size_x = 32, local_size_y = 32) in;



layout(binding = 0, set = 0, rgba8) uniform image2D image;

layout(binding = 1, set = 0) buffer rtMaskBuffer{
	uint rtMask[];
};

layout(push_constant, std430) uniform pushConstant{
	uint width;
	uint height;
};

#if SHARED_MEMORY
shared vec4 sharedData[LOCAL_SIZE_Y][LOCAL_SIZE_X];
#endif

//TODO: edge handling
void main()
{
	uvec2 target = gl_GlobalInvocationID.xy;
		
	if(target.y < 0 || target.y * 2 + 1 >= height) return;
	if(target.x < 0 || target.x >= width) return;
	
#if SHARED_MEMORY	//SM
	uvec2 localId = gl_LocalInvocationID.xy;
	target.y *= 2;
	sharedData[localId.y][localId.x] = imageLoad(image, ivec2(target));
	
	memoryBarrierShared();
	barrier();

	vec4 upColor = sharedData[localId.y][localId.x];
	vec4 downColor;
	if(localId.y == LOCAL_SIZE_Y - 1)
		downColor = imageLoad(image, ivec2(target.x, target.y + 2));
	else
		downColor = sharedData[localId.y + 1][localId.x];
	target.y += 1;
#else				//GM
	target.y = target.y * 2 + 1;
	
	vec4 upColor = imageLoad(image, ivec2(target.x, target.y-1));
	vec4 downColor = imageLoad(image, ivec2(target.x, target.y+1));
#endif
	vec4 finalColor = vec4(0.0, 0.0, 0.0, 0.0);
	float psnr = calculatePSNR(upColor.xyz, downColor.xyz);
	if(psnr > 40){
		finalColor = (upColor + downColor) / 2;
		imageStore(image, ivec2(target), finalColor);
	}
	else{
		rtMask[target.y * width + target.x] = 1;
	}
//	finalColor = (upColor + downColor) / 2;
//		imageStore(image, ivec2(target), finalColor);
}