apply plugin: 'com.android.application'
apply from: '../gradle/outputfilename.gradle'

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "sogang.graphics.vulkanfullrt"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters rootProject.ext.abiFilters
        }
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++2a"
                arguments "-DANDROID_STL=c++_shared", '-DANDROID_TOOLCHAIN=clang'
            }
        }
    }
    sourceSets {
        main.assets.srcDirs = ['assets']
    }
    signingConfigs {
        release {
            keyAlias "key0"
            keyPassword "241004"
            storeFile file("C:\\AndroidKeys\\releaseKey.jks")
            storePassword "241004"
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path project.file("CMakeLists.txt")
        }
    }
}

task copyTask {
    copy {
        from '../../common/res/drawable'
        into "src/main/res/drawable"
        include 'icon.png'
    }

    copy {
        from rootProject.ext.shaderPath + 'glsl/base'
        into 'assets/shaders/glsl/base'
        include '*.spv'
    }

    copy {
        from rootProject.ext.shaderPath + 'glsl/VulkanFullRT'
        into 'assets/shaders/glsl/VulkanFullRT'
        include '*.spv'
    }

    // gltf models
//    copy {
////        from rootProject.ext.assetPath + 'models/cornellBox'
////        into 'assets/models/cornellBox'
////
////        from rootProject.ext.assetPath + 'models/suntemple_simple'
////        into 'assets/models/suntemple_simple'
////
////        from rootProject.ext.assetPath + 'models/suntemple_etc1s'
////        into 'assets/models/suntemple_etc1s'
////
////        from rootProject.ext.assetPath + 'models/sponza_multi_blas_transparent'
////        into 'assets/models/sponza_multi_blas_transparent'
////
////        from rootProject.ext.assetPath + 'models/sponza_etc1s'
////        into 'assets/models/sponza_etc1s'
////
////       from rootProject.ext.assetPath + 'models/bistroexterior_etc1s'
////       into 'assets/models/bistroexterior_etc1s'
//        include '*.*'
//    }

    // ply models
    copy {
//        from rootProject.ext.assetPath + '3DGRTModels/hotdog'
//        into 'assets/3DGRTModels/hotdog'
//        include 'hotdog2_3dgrt.ply', 'transforms_val.json'

//        from rootProject.ext.assetPath + '3DGRTModels/mic'
//        into 'assets/3DGRTModels/mic'
//        include 'mic_3dgrt.ply', 'transforms_val.json'
//
//        from rootProject.ext.assetPath + '3DGRTModels/ship'
//        into 'assets/3DGRTModels/ship'
//        include 'ship_3dgrt.ply', 'transforms_val.json'
//
//        from rootProject.ext.assetPath + '3DGRTModels/lego'
//        into 'assets/3DGRTModels/lego'
//        include 'lego_3dgrt.ply', 'transforms_val.json'
//
        from rootProject.ext.assetPath + '3DGRTModels/drums'
        into 'assets/3DGRTModels/drums'
        include 'drums_3dgrt.ply', 'transforms_val.json'
//
//        from rootProject.ext.assetPath + '3DGRTModels/chair'
//        into 'assets/3DGRTModels/chair'
//        include 'chair_3dgrt.ply', 'transforms_val.json'
//
//        from rootProject.ext.assetPath + '3DGRTModels/room'
//        into 'assets/3DGRTModels/room'
//        include 'room_3dgrt.ply', 'transforms_val.json'
//
//        from rootProject.ext.assetPath + '3DGRTModels/counter'
//        into 'assets/3DGRTModels/counter'
//        include 'counter_3dgrt.ply', 'transforms_val.json'
//
//        from rootProject.ext.assetPath + '3DGRTModels/kitchen'
//        into 'assets/3DGRTModels/kitchen'
//        include 'kitchen_3dgrt.ply', 'transforms_val.json'
//
//        from rootProject.ext.assetPath + '3DGRTModels/bonsai'
//        into 'assets/3DGRTModels/bonsai'
//        include 'bonsai_3dgrt.ply', 'transforms_val.json'
//
//        from rootProject.ext.assetPath + '3DGRTModels/bicycle'
//        into 'assets/3DGRTModels/bicycle'
//        include 'bicycle_3dgrt.ply', 'transforms_val.json'
//
//        from rootProject.ext.assetPath + '3DGRTModels/garden'
//        into 'assets/3DGRTModels/garden'
//        include 'garden_3dgrt.ply', 'transforms_val.json'
    }
}

preBuild.dependsOn copyTask